name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: dirly-466300
  SERVICE_NAME: prompttovideo
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Create Artifact Registry Repository
      run: |
        gcloud artifacts repositories create prompttovideo \
          --repository-format=docker \
          --location=us-central1 \
          --description="Docker repository for PromptToVideo app" || true
    
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Build and Push Container
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/prompttovideo/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/prompttovideo/${{ env.SERVICE_NAME }}:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/prompttovideo/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --timeout 300 \
          --concurrency 80 \
          --max-instances 5 \
          --set-env-vars DATABASE_URL="postgresql://prompttovideo:PromptToVideo2024!@/prompttovideo?host=/cloudsql/${{ env.PROJECT_ID }}:us-central1:prompttovideo-db,GCS_BUCKET_NAME=prompt-veo-videos,VEO_MOCK_MODE=false,FLASK_ENV=production,GOOGLE_APPLICATION_CREDENTIALS=/app/veo.json" \
          --add-cloudsql-instances ${{ env.PROJECT_ID }}:us-central1:prompttovideo-db \
          --service-account prompttovideo-runner@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
    
    - name: Show Service URL
      run: |
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --format 'value(status.url)' 