name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: dirly-466300
  SERVICE_NAME: prompttovideo
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --timeout 300 \
          --concurrency 80 \
          --max-instances 5 \
          --set-env-vars DATABASE_URL="postgresql://prompttovideo:PromptToVideo2024!@/prompttovideo?host=/cloudsql/${{ env.PROJECT_ID }}:us-central1:prompttovideo-db" \
          --set-env-vars GCS_BUCKET_NAME="prompt-veo-videos" \
          --set-env-vars VEO_MOCK_MODE="false" \
          --set-env-vars FLASK_ENV="production" \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS="/app/veo.json" \
          --add-cloudsql-instances ${{ env.PROJECT_ID }}:us-central1:prompttovideo-db \
          --service-account prompttovideo-runner@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
    
    - name: Show Service URL
      run: |
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --format 'value(status.url)' 